name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install dependency
        run: npm ci
      - name: build
        run: |
          npm run start
      - name: report
        if: failure()
        run: |
          echo 'build failed'
      - name: success
        run: |
          echo 'build successful'
